* Examples of using Kawa Scheme on Android

- KawaHello is a simple hello world application
- LunarLander is a reimplementation of the SDK example
- LearningAndroid-chapter{6,7,8,9,10} are implementations of the main
  projects for most of the chapters from Marko Garneta's "Learning
  Android"

These were written while I was figuring out if Kawa can be used for
Android development, and how one might do so as there are few examples
of this and many Android&Kawa-specific quirks to figure out. All
examples try to mostly stay true to their source however badly
designed that source was. As such this isn't a good place to look for
good Scheme style or idiomatic Kawa.

To get started you'll need a custom build for Kawa:
#+BEGIN_SRC sh
svn -q checkout svn://sourceware.org/svn/kawa/trunk kawa
./configure --with-android=$ANDROID_HOME/platforms/$ANDROID_PLATFORM/android.jar --disable-xquery --disable-jemacs
#+END_SRC
and you will need to place kawa-1.11.jar in the libs/ directory in for each of the examples.

To create a new project you can use:
#+BEGIN_SRC sh
android create project --target $ANDROID_PLATFORM --name $PROJECT --activity $ACTIVITY --path $PROJECT --package kawa.android
cd $PROJECT
rm $PROJECT/src/kawa/android/$ACTIVITY.jar
touch $PROJECT/src/kawa/android/$ACTIVITY.scm
ln -s $KAWA_INSTALL_DIR/kawa-1.11.jar $PROJECT/libs/kawa.jar
(cd $PROJECT; patch < ../build-xml.patch)
#+END_SRC

You may need to update local.properties in each of the examples
directory to change the path to the SDK.

Each directory contains a simple make-and-send script which builds the project, uploads it to the emulator and starts it up.

This has been tested with Android SDK r15.

LearningAndroid examples need to a copy of jtwitter.jar and
signpost-core-1.2.1.1.jar from
http://www.winterwell.com/software/jtwitter.php in each of their libs
directory.
