* Examples of using Kawa Scheme on Android

- KawaHello is a simple hello world application
- LunarLander is a reimplementation of the SDK example
- LearningAndroid-chapter{6,7,8,9,10} are implementations of the main
  projects for most of the chapters from Marko Garneta's "Learning
  Android"

These were written while I was figuring out if Kawa can be used for
Android development and how to work out various Android&Kawa-specific
quirks. All examples try to mostly stay true to their source however
badly designed that source was. As such this isn't a good place to
look for good Scheme style or idiomatic Kawa.

To get started you'll need a custom build for Kawa, this will fetch
the latest svn sources
#+BEGIN_SRC sh
bin/setup-kawa
#+END_SRC
and to get the examples to work you need to set them up
#+BEGIN_SRC sh
bin/setup-examples
#+END_SRC

To create a new project you can use:
#+BEGIN_SRC sh
bin/make-project android-14 HelloWorld hello
#+END_SRC
the arguments are: the platform/api level, the project name and the
original activity name. This calls 'android create project' and
patches the resulting build.xml file. It will create a trivial
application that displays a message. Sources are in
<project-name>/src/kawa/android/<activity>.scm.

The resulting directory contains a make-and-send script which builds
the project, uploads it to the emulator or to the phone and starts it
up.

You may need to update local.properties in each of the examples
directory to change the path to the SDK.

This has been tested with Android SDK r15.

LearningAndroid examples need to a copy of jtwitter.jar and
signpost-core-1.2.1.1.jar from
http://www.winterwell.com/software/jtwitter.php in each of their libs
directory.
